{extends 'template:baseTemplate'}
{block 'content'}
<div class="container">

    {'mFilter2' | snippet : [
    'paginator' => 'pdoPage@mfilter2',
    'class' => 'msProduct',
    'element' => 'msProducts',
    'parents' => $_modx->resource.id,
    'includeContent' => 1,
    'aliases' => '
    resource|parent-categories==categories,
    ',
    'limit' => 12,
    'filters' => '
    ms|price:number,
    ms|vendor:vendors,
    parent:categories,
    msoption|color,
    msoption|depth:number,
    msoption|loadingLaundry:number,
    msoption|typeOfLoad,
    msoption|numberOfRotation:number,
    msoption|energyClass,
    msoption|width:number,
    msoption|height:number,
    msoption|typeOfDrying,
    msoption|typeOfDishwasher,
    msoption|numberOfSets,
    msoption|locationOfFreezer,
    msoption|typeOfRefrigeration,
    msoption|typeOfFreezer,
    msoption|totalV:number,
    msoption|vOfRefrigerator:number,
    msoption|vOfFreezer:number,
    msoption|noiseLevel:number,
    msoption|freezingPower:number,
    msoption|autonomousColdStorage,
    msoption|cameraType,
    msoption|minTemp:number,
    msoption|features,
    ',
    'tplFilter.outer.msoption|width' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|width' => 'tpl.mFilter2.filter.number1',
    'tplFilter.outer.msoption|height' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|height' => 'tpl.mFilter2.filter.number1',
    'tplFilter.outer.msoption|totalV' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|totalV' => 'tpl.mFilter2.row.number1',
    'tplFilter.outer.msoption|vOfRefrigerator' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|vOfRefrigerator' => 'tpl.mFilter2.row.number1',
    'tplFilter.outer.msoption|vOfFreezer' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|vOfFreezer' => 'tpl.mFilter2.row.number1',
    'tplFilter.outer.msoption|noiseLevel' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|noiseLevel' => 'tpl.mFilter2.row.number1',
    'tplFilter.outer.msoption|freezingPower' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|freezingPower' => 'tpl.mFilter2.row.number1',
    'tplFilter.outer.msoption|minTemp' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|minTemp' => 'tpl.mFilter2.row.number1',

    'tplFilter.row.msoption|typeOfDrying' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|typeOfDrying' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|typeOfDishwasher' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|typeOfDishwasher' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|numberOfSets' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|numberOfSets' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|locationOfFreezer' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|locationOfFreezer' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|typeOfRefrigeration' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|typeOfRefrigeration' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|typeOfFreezer' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|typeOfFreezer' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|autonomousColdStorage' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|autonomousColdStorage' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|cameraType' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|cameraType' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|features' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|features' => 'tpl.mfilter2.filter.outer.checkbox',

    'tplFilter.row.msoption|energyClass' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|energyClass' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.outer.ms|price' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.ms|price' => 'tpl.mFilter2.row.number1',
    'tplFilter.outer.msoption|depth' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|depth' => 'tpl.mFilter2.row.number1',
    'tplFilter.outer.msoption|loadingLaundry' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|loadingLaundry' => 'tpl.mFilter2.row.number1',
    'tplFilter.outer.msoption|numberOfRotation' => 'tpl.mFilter2.filter.slider1',
    'tplFilter.row.msoption|numberOfRotation' => 'tpl.mFilter2.row.number1',
    'tplFilter.outer.ms|vendor' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.ms|vendor' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.row.resource|parent' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.resource|parent' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|color' => 'tpl.mFilter2.filter.checkbox',
    'tplFilter.outer.msoption|color' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplFilter.row.msoption|typeOfLoad' => 'tpl.mFilter2.row.checkbox',
    'tplFilter.outer.msoption|typeOfLoad' => 'tpl.mfilter2.filter.outer.checkbox',
    'tplOuter' => 'tpl.mFilter2.category.outer',
    'sort' => 'ms|price:asc',
    'tpls' => 'productsByCard,productsByList,productsByTableRow'
    ]}


</div>
{/block}